# Generated by Django 5.1.1 on 2024-10-04 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_fixedexpense'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedexpense',
            name='end_month',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='fixedexpense',
            name='created_at',
            field=models.DateField(),
        ),
    ]
